// Lo que dice el botón «i» de cada widget. Regla (Randall 6-sep): que cualquiera entienda qué muestra,
// sin palabras técnicas; primero qué es, luego cómo se cuenta. «Las fechas elegidas» = el periodo del calendario.
export const GLOSARIO = {
  'Leads asignados': 'Cuántos leads se repartieron a los asesores en las fechas elegidas (cuenta la fecha en que se le asignó al asesor que lo tiene hoy), estén como estén hoy: activos, ganados o descartados.',
  'Clientes cerrados': 'Ventas registradas en la app de comisiones en las fechas elegidas (por mes de venta, sin canceladas). Solo si el corte no trae la app se usan los ganados del CRM.',
  'Leads activos': 'Leads que se asignaron en las fechas elegidas y que siguen en juego: todavía no se cierran como venta ni se descartan.',
  'Presupuesto': 'Suma del precio cotizado a los leads activos del asesor.',
  'Llamadas': 'Cuántas llamadas se registraron en el CRM en las fechas elegidas. Contestada: la llamada duró algo. Sin contestar: duró cero.',
  'Tareas': 'Tres cosas: tareas que el asesor terminó en las fechas elegidas, tareas que vencían hoy y no se hicieron, y leads activos que no tienen ninguna tarea pendiente (nadie los está siguiendo).',
  'Tareas completadas': 'Tareas que los asesores marcaron como terminadas en el CRM en las fechas elegidas.',
  'Sin tarea': 'Lead asignado que no tiene ninguna tarea pendiente: se terminó la última y no se programó el siguiente paso.',
  'Cumplimiento': 'Qué parte de la meta ya se vendió: lo vendido en las fechas elegidas contra la parte de la meta que toca a esas fechas.',
  'Conversión': 'De cada 100 leads asignados en las fechas elegidas, cuántas ventas se registraron en la app de comisiones en esas mismas fechas.',
  'Cotizaciones generadas': 'Imágenes de cotización que los asesores generaron en el cotizador en las fechas elegidas, con y sin lead en Kommo. Cada cotización puede llevar hasta 3 métodos de pago: la tabla de métodos cuenta en cuántas cotizaciones aparece cada uno y la de combinaciones cuenta cotizaciones por el conjunto exacto de métodos que llevaban.',
  'Ventas reales': 'Ventas que sí se cobraron según la app de comisiones (sin canceladas), por el mes en que se vendieron y unidas al asesor por su nombre. El CRM a veces marca la venta antes o después, y con otro monto.',
  'Tasa de pérdida': 'De cada 100 leads asignados en las fechas elegidas, cuántos se descartaron. Un lead ganado o descartado deja de ser activo: ya no se le revisa actividad ni tareas.',
  'Salud operativa': 'Leads asignados en las fechas elegidas dentro de los embudos Ventas y Hunting, separados entre los que ya tienen precio cotizado y los que todavía no.',
  'Embudo': 'Cuántos leads activos hay hoy en cada etapa del proceso de venta, de la primera a la última. Los ya ganados o descartados no aparecen.',
  'Monto cotizado': 'Suma del precio cotizado de los leads que hoy están en cada etapa del embudo Ventas.',
  'Tiempo promedio': 'Cuántos días llevan, en promedio, los leads en la etapa donde están hoy sin que nadie los mueva.',
  'Tareas hoy': 'Tareas que vencen hoy (más las que el asesor se puso aquí) contra las que ya terminó hoy. Las vencidas de días anteriores se cuentan aparte.',
  'Actividades': 'Todo lo que el asesor registró hoy: llamadas, tareas terminadas, cotizaciones entregadas y levantamientos solicitados.',
  'Actividad': 'Qué tanto trabajó el asesor cada día o cada semana: llamadas, tareas terminadas, cotizaciones entregadas y levantamientos solicitados. Cada bolita es un conteo; entre más grande, más actividad. Con más de tres semanas se agrupa por semana y con más de seis meses por mes; un clic en una semana o un mes lo abre por día.',
  'Actividad de hoy': 'Lo que registraste en el CRM, contado por hora de hoy (Día) o por día de esta semana (Semana): llamadas, tareas terminadas, cotizaciones y levantamientos.',
  'Meta': 'Cuánto debe vender cada asesor al mes, en pesos: $800,000 para todos, salvo quien tenga una meta propia en Configuración. Para otras fechas se toma la parte proporcional de los días elegidos.',
  'Esperado a hoy': 'La parte de la meta que ya debería estar vendida hoy si se vendiera parejo todos los días del periodo.',
  'Tipo de vendedor': 'Leads = vende con los leads del CRM. Cambaceo = vende de puerta en puerta sin CRM: solo existe en la app de comisiones, por eso sus columnas de leads y actividad salen en «—» y no entra en Perfiles. Leads + cambaceo = las dos cosas. Otro = ninguna de las anteriores (sin CRM sale igual que cambaceo en las columnas). Se fija en Configuración; si no, es automático: Cambaceo cuando el CRM del vendedor es «Sin CRM». El CRM también se declara en Configuración (columna CRM): solo informa al líder de ventas, los datos se siguen leyendo de donde estén.',
  'Ritmo': 'El vendido sale de la app de comisiones (por mes de venta, sin canceladas); el CRM solo si el corte no trae la app. Si la venta va al paso de la meta. La meta se reparte parejo entre los días del periodo: al día 10 de 30 ya debería ir vendida una tercera parte. «Arriba del ritmo» es ir adelantado; «abajo del ritmo», atrasado. En el medidor, la marca gris es lo que tocaría llevar hoy y la negra la meta completa.',
  'Vendido': 'Contrato total de las ventas de la app de comisiones en las fechas elegidas (por mes de venta). Solo si el corte no trae la app se suma el precio de los ganados del CRM.',
  'Asignación': 'Si al asesor le siguen llegando leads nuevos. Al quitarlo: en Kommo entra a la lista «Sanciones 24h» y no recibe leads hasta las 10:00 del día siguiente; en HubSpot sale de su equipo de ventas hasta que se reactive. Los leads que ya tiene no se tocan.',
  'Cotizaciones': 'Cuántos leads recibieron su cotización en las fechas elegidas: cuenta la primera vez que el lead pasó a «Propuesta entregada» (una por lead) y se le atribuye al asesor que lo tiene hoy, aunque después lo hayan regresado de etapa. Si vuelven a cotizar el mismo lead, cuenta aparte como recotización. En HubSpot hay fechas desde el 4 de agosto de 2026; lo anterior solo cuenta si hoy sigue en esa etapa.',
  'Levantamientos': 'Visitas técnicas (levantamientos) que se solicitaron en las fechas elegidas.',
  'Cotizado vigente': 'Dinero que hay en juego: suma del precio cotizado de los leads activos cuya cotización tiene 90 días o menos. Si el lead no tiene fecha de cotización, se cuenta desde que se asignó.',
  'Antigüedad': 'Días que han pasado desde que se cotizó el lead (o desde que se asignó, si no hay fecha de cotización). Pasados 90 días ya no se considera una venta viva: debería descartarse.',
  'Pipeline 10×': 'Regla acordada con Alejandro: para llegar a la meta hay que tener cotizado vigente por 10 veces la meta del mes.',
  'Tasa de asignación': 'De los leads que llegaron a Kommo en las fechas elegidas, cuántos ya tienen asesor. Los que nadie ha tomado quedan en la cuenta del administrador y no cuentan al filtrar por equipo o asesor.',
  'Primer contacto': 'Cuánto tarda el asesor en hacer algo con un lead nuevo: horas desde que se le asignó hasta su primera llamada o tarea terminada. Se muestra el valor de en medio (la mitad de los leads tardó menos, la otra mitad más). «Sin contacto»: lleva más de un día asignado y no se le ha hecho nada. Solo Kommo: en HubSpot las llamadas y tareas no vienen unidas al lead.',
  'Intentos': 'Cuántas veces se intentó contactar al lead: llamadas registradas más mensajes que le mandó el asesor. Solo Kommo.',
  'Primer contacto vencido': 'Leads activos a los que se les pasó la fecha de la tarea de primer contacto. Solo Kommo distingue ese tipo de tarea.',
  'Estancados': 'Leads activos que llevan más de 7 días sin ningún cambio en el CRM.',
  'Perfil': 'Clasifica a cada asesor por dos cosas: cuánta actividad registra (llamadas, tareas terminadas, cotizaciones y levantamientos) y cuánto vende. La línea que parte cada eje es el punto medio del grupo: la mitad de los asesores queda arriba y la mitad abajo. Mantener: vende y trabaja. Capacitar: trabaja mucho pero vende poco. Revisar: vende sin actividad registrada. Salida: ni actividad ni venta.',
  'Razón de descarte': 'El motivo que el asesor eligió en el CRM al descartar el lead, contado por la fecha en que lo descartó.',
  'Ranking': 'Asesores ordenados por lo que vendieron en las fechas elegidas según la app de comisiones (vendedores sin asesor en el CRM no aparecen aquí; sí en la tabla «Ventas reales»). En la barra, la marca negra es su meta para esas fechas y la gris lo que debería llevar hoy.',
  'Mi día': 'Tu resumen de hoy: tareas terminadas contra las que tocaban, ventas del día y cómo vas en el mes contra tu meta, llamadas hechas y leads nuevos que te asignaron hoy.',
  'Tareas del día': 'Tus tareas del CRM que vencen hoy o vencieron en los últimos 14 días, más las que agregues aquí. Un clic cambia el estado: pendiente, en curso, hecha.',
  'Contrato total': 'Suma del monto de contrato de las ventas registradas en la app de comisiones en las fechas elegidas. Las canceladas no cuentan.',
  'Precio por panel': 'Contrato total entre los paneles vendidos: cuánto se cobra, en promedio, por cada panel.',
  'Ticket promedio': 'Contrato total entre el número de ventas: cuánto vale, en promedio, cada venta.',
  'Paneles vendidos': 'Suma de los paneles de todas las ventas en las fechas elegidas.',
  'Enganches pagados': 'Cuántas ventas ya tienen el enganche pagado, según la casilla que marca el vendedor en la app, y qué parte del total son.',
  'Mes contra mes': 'Cuánto subió o bajó el contrato total del último mes con ventas contra el mes anterior. Toma todos los meses, no solo las fechas elegidas.',
  'Ingresos por mes': 'Contrato total de cada mes y, debajo, cuántas ventas fueron. Muestra todos los meses que hay en la app, no solo las fechas elegidas, para ver la tendencia completa.',
  'Top vendedores': 'Los diez vendedores con más contrato en las fechas elegidas, con su número de ventas.',
  'Origen de las ventas': 'Qué canal trae más dinero: el contrato total por el origen que capturó el vendedor (redes sociales, referido, directo, expansión). «Sin origen» es lo que falta por capturar.',
  'Contrato por zona': 'Contrato total por la zona tal como está en la app de comisiones (incluye comercial y foráneo).',
  'Forma de pago': 'Contrato total por forma de pago: contado, financiamiento, meses sin intereses, Mejoravit, FIDE.',
  'Ticket por forma de pago': 'Contrato promedio de cada venta según su forma de pago, con cuántas ventas hubo de cada una. Así se ve qué formas traen tickets grandes y con cuánto volumen.',
  'Tamaño de venta': 'Cuántas ventas hubo de cada tamaño, medido en paneles. Las ventas sin paneles capturados no entran.',
  'Precio por panel por asesor': 'Contrato total entre paneles vendidos de cada vendedor: quién cobra más por panel. Los diez más altos.',
  'Precio por panel por mes': 'Contrato total entre paneles vendidos de cada mes. Toma todos los meses de la app.',
  'Región': 'R1 = Monterrey y Saltillo; R2 = Torreón y Monclova. «Todas» incluye también Chihuahua, comercial y foráneo.',
  'Captura': 'Una venta está completa cuando el vendedor ya capturó el origen y la liga de HubSpot (a tres vendedores no se les pide la liga). Incompleta es lo que falta por capturar.',
  'Leaderboard': 'Quién va ganando hoy: asesores ordenados por ventas cerradas hoy y, en empate, por actividades registradas hoy.',
} as const
export type Termino = keyof typeof GLOSARIO
