// Definiciones que salen en el botón «i». Una frase, sin jerga, con la regla de cálculo.
export const GLOSARIO = {
  'Leads activos': 'Leads asignados en el rango que no están ganados ni perdidos.',
  'Presupuesto': 'Suma del presupuesto (precio) de los leads activos del asesor.',
  'Llamadas': 'Llamadas registradas en el rango. Contestada = con duración; sin contestar = duración cero.',
  'Tareas': 'Completadas en el rango, vencidas hoy en sus leads activos y leads activos sin ninguna tarea abierta.',
  'Sin tarea': 'Lead asignado sin ninguna tarea abierta: se cerró la anterior y no quedó seguimiento.',
  'Cumplimiento': 'Monto vendido en el rango (por fecha de cierre) entre la meta prorrateada al rango.',
  'Conversión': 'Ventas cerradas en el rango entre leads asignados en el rango. Es por periodo, no por cohorte.',
  'Ventas reales': 'Ventas registradas en la app de comisiones por mes de venta, sin canceladas, cruzadas con el asesor del CRM por nombre. Es la venta que sí se cobró; el CRM marca ganado antes o después y a veces con otro monto.',
  'Tasa de pérdida': 'Leads asignados en el rango que terminaron en perdido, entre todos los asignados en el rango (activos + ganados + perdidos). Ganados y perdidos dejan de ser leads activos: no se les revisa actividad ni tareas; solo cuentan para ventas, cierre, pérdidas y razones de pérdida.',
  'Salud operativa': 'Leads asignados en Ventas o Hunting con última asignación en el rango, partidos por si ya traen presupuesto.',
  'Monto cotizado': 'Suma del presupuesto de los leads que hoy están en cada etapa del embudo Ventas.',
  'Tiempo promedio': 'Días promedio que los leads llevan en su etapa actual (días sin cambio en el CRM).',
  'Tareas hoy': 'Tareas que vencen hoy más las propias, contra las ya completadas hoy. El rezago vencido se cuenta aparte.',
  'Actividades': 'Actividades registradas hoy: llamadas, tareas completadas, cotizaciones y levantamientos.',
  'Meta': 'Meta mensual de venta en pesos por asesor: $800,000 para todos (VENTAS_META_MXN) salvo quien tenga la suya en VENTAS_METAS. Se prorratea al rango elegido.',
  'Esperado a hoy': 'Parte de la meta del rango que ya debería estar vendida a día N de M del rango, por días naturales y con hoy contado completo.',
  'Ritmo': 'La meta del periodo repartida por días naturales: a día N de M ya debería estar vendido N/M de la meta. «Arriba del ritmo» es vendido por encima de esa parte; «abajo del ritmo», por debajo. La marca gris del medidor es esa parte; la negra, la meta completa.',
  'Vendido': 'Suma del presupuesto de las ventas cerradas en el rango, por fecha de cierre.',
  'Asignación': 'Si el asesor recibe leads nuevos. Quitar = en Kommo entra a la lista «Sanciones 24h» del Sheet (sin leads nuevos hasta las 10:00 del día siguiente, cuando el corte automático reevalúa); en HubSpot sale de su equipo de ventas hasta que se reactive. No borra ni reasigna los leads que ya tiene.',
  'Cotizado vigente': 'Presupuesto de los leads activos con monto (asignados en el rango) cuya cotización tiene 90 días o menos. Sin fecha de cotización, cuenta desde la asignación.',
  'Antigüedad': 'Días desde la fecha de cotización del lead (o desde su asignación si no la tiene). Lo de más de 90 días ya no cuenta como pipeline vivo: debería ir a perdido.',
  'Pipeline 10×': 'Regla acordada con Alejandro: para vender la meta hay que traer cotizado vigente por 10 veces la meta mensual.',
  'Tasa de asignación': 'Leads de Kommo creados en el rango que ya están asignados a un asesor, entre todos los que llegaron. Con filtro de asesor o equipo cuenta por el responsable actual del lead; los no asignados cuelgan de la cuenta admin y quedan fuera.',
  'Primer contacto': 'Horas desde la asignación hasta la primera llamada o tarea completada del lead. Mediana de los asignados en el rango; «sin contacto» = más de un día asignado y nada registrado. Solo Kommo: en HubSpot las tareas y llamadas no vienen ligadas al deal.',
  'Intentos': 'Llamadas registradas en el lead (campo Llamadas) y mensajes salientes del asesor. Solo Kommo; en HubSpot no hay dato por deal.',
  'Primer contacto vencido': 'Leads activos cuya tarea de primer contacto ya venció. Solo Kommo distingue el tipo de tarea.',
  'Estancados': 'Leads activos con más de 7 días sin cambio en el CRM.',
  'Perfil': 'Cuadrante actividad × venta (los cuatro perfiles de Samuel): la mediana del grupo parte cada eje. Mucha actividad sin venta = capacitar; venta sin actividad = revisar; nada de nada = salida.',
  'Razón de descarte': 'Razón de pérdida registrada en el CRM al descartar el lead, contada por la fecha del descarte.',
  'Ranking': 'Asesores ordenados por monto vendido en el rango. La marca negra es su meta prorrateada al rango; la gris, lo esperado a hoy.',
} as const
export type Termino = keyof typeof GLOSARIO
