// Definiciones que salen en el botón «i». Una frase, sin jerga, con la regla de cálculo.
export const GLOSARIO = {
  'Leads activos': 'Leads asignados en el rango que no están ganados ni perdidos.',
  'Presupuesto': 'Suma del presupuesto (precio) de los leads activos del asesor.',
  'Llamadas': 'Llamadas registradas en el rango. Contestada = con duración; sin contestar = duración cero.',
  'Tareas': 'Completadas en el rango, vencidas hoy en sus leads activos y leads activos sin ninguna tarea abierta.',
  'Sin tarea': 'Lead asignado sin ninguna tarea abierta: se cerró la anterior y no quedó seguimiento.',
  'Cumplimiento': 'Monto vendido en el rango (por fecha de cierre) entre la meta prorrateada al rango.',
  'Conversión': 'Ventas cerradas en el rango entre leads asignados en el rango. Es por periodo, no por cohorte.',
  'Salud operativa': 'Leads asignados en Ventas o Hunting con última asignación en el rango, partidos por si ya traen presupuesto.',
  'Monto cotizado': 'Suma del presupuesto de los leads que hoy están en cada etapa del embudo Ventas.',
  'Tiempo promedio': 'Días promedio que los leads llevan en su etapa actual (días sin cambio en el CRM).',
  'Tareas hoy': 'Tareas que vencen hoy más las propias, contra las ya completadas hoy. El rezago vencido se cuenta aparte.',
  'act.': 'Actividades registradas hoy: llamadas, tareas completadas, cotizaciones y levantamientos.',
  'Meta': 'Meta mensual de venta en pesos por asesor: $800,000 para todos (VENTAS_META_MXN) salvo quien tenga la suya en VENTAS_METAS. Se prorratea al rango elegido.',
  'Esperado a hoy': 'Parte de la meta del rango que ya debería estar vendida según el tiempo transcurrido (regla de tres).',
  'Vendido': 'Suma del presupuesto de las ventas cerradas en el rango, por fecha de cierre.',
  'Cotizado vigente': 'Presupuesto de los leads activos con monto (asignados en el rango) cuya cotización tiene 90 días o menos. Sin fecha de cotización, cuenta desde la asignación.',
  'Antigüedad': 'Días desde la fecha de cotización del lead (o desde su asignación si no la tiene). Lo de más de 90 días ya no cuenta como pipeline vivo: debería ir a perdido.',
  'Pipeline 10×': 'Regla acordada con Alejandro: para vender la meta hay que traer cotizado vigente por 10 veces la meta mensual.',
  'Tasa de asignación': 'Leads de Kommo creados en el rango que ya están asignados a un asesor, entre todos los que llegaron. No aplica el filtro de equipo: los no asignados no tienen dueño.',
  'Primer contacto': 'Horas desde la asignación hasta la primera llamada o tarea completada del lead. Mediana de los asignados en el rango; «sin contacto» = más de un día asignado y nada registrado. Solo Kommo: en HubSpot las tareas y llamadas no vienen ligadas al deal.',
  'Intentos': 'Llamadas registradas en el lead (campo Llamadas) y mensajes salientes del asesor. Solo Kommo; en HubSpot no hay dato por deal.',
  'PC vencidas': 'Leads activos cuya tarea de primer contacto ya venció. Solo Kommo distingue el tipo de tarea.',
  'Estancados': 'Leads activos con más de 7 días sin cambio en el CRM.',
  'Perfil': 'Cuadrante actividad × venta (los cuatro perfiles de Samuel): la mediana del grupo parte cada eje. Mucha actividad sin venta = capacitar; venta sin actividad = revisar; nada de nada = salida.',
  'Razón de descarte': 'Razón de pérdida registrada en el CRM al descartar el lead, contada por la fecha del descarte.',
  'Ranking': 'Asesores ordenados por monto vendido en el rango. La marca negra es su meta prorrateada al rango; la gris, lo esperado a hoy.',
} as const
export type Termino = keyof typeof GLOSARIO
